pull_request_rules:
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
  - name: remove outdated reviews
    conditions:
      - base=master
    actions:
      dismiss_reviews: {}
  - name: Automatic merge
    conditions:
      - label!=🚧 Work in Progress
      - "#approved-reviews-by>=1"
      - status-success=Travis CI - Pull Request
      - status-success=Travis CI - Branch
      - status-success=build (8.x)
      - status-success=build (10.x)
      - status-success=build (12.x)
      - status-success=codecov/project
      - status-success=codecov/patch
      - status-success=DeepCode
      - status-success=Codacy/PR Quality Review
      - status-success=Mergeable
      - status-success=license/cla
    actions:
      merge:
        method: merge
      label:
        add: ["Auto merge"]
  - name: automatic merge if author is MHuiG
    conditions:
      - author=MHuiG
      - status-success=build (12.x)
    actions:
      merge:
        method: merge
      label:
        add: ["Auto merge"]
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=build (12.x)
    actions:
      merge:
        method: merge
      label:
        add: ["Auto merge","Build","🛠 Improvement"]
  - name: automatic merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - status-success=build (12.x)
    actions:
      merge:
        method: merge
      label:
        add: ["Auto merge","Build","🛠 Improvement"]
  - name: automatic merge for ImgBot pull requests
    conditions:
      - author=imgbot[bot]
      - status-success=build (12.x)
    actions:
      merge:
        method: merge
      label:
        add: ["Auto merge","🛠 Improvement"]
