language: node_js
node_js:
  - 8
os: linux

install:
  - npm install -g eslint
  - npm install

script:
  - npm run build
  - npm test

after_script:
  - npm run check


notifications:
  email: false
